### ISSUE TITLE
MovementCoponent::checkVelocity fa muovere il player a velocità maggiori se si muove in diagonale

### ISSUE THREAD

**Issue by maltempoLuca** [Puccio98/SFML#4]
Il controllo della velocità massima viene fatto allo stesso modo per entrambe le direzioni, questo permette al giocatore di correre più veloce in diagonale.

Correggere in modo che il che la velocità massima faccia riferimento al Modulo del vettore velocità e non alle singole componenti

**Comment by alessandromanca98** [comment]
adesso il personaggio si muove entro la velocità massima anche diagonalmente
