### ISSUE TITLE
Sistema di personaggio+arma a singola sprite ma doppia hitbox!!!!

### ISSUE THREAD

**Issue by maltempoLuca** [Puccio98/SFML#54]

**Comment by alessandromanca98** [comment]
Praticamente lato photoshop funzionerà così:

avrò due sheet, uno per le animazioni del personaggio (senza oggetto) e sopra questo sheet, su diversi layer disegnerò le armi, facendo in modo che l'origine dell'arma coincida con determinate coordinate x y e che tutti i layer delle armi combacino. A quel punto trasferisco le animazioni della spada in un altro file tenendo a mente che la sprite di un singolo frame dell'arma avrà le dimensioni dell'arma più grande che intendiamo aggiungere, e poi a livello di codice viene fatto uno shift per far combaciare la sprite dell'arma con la mano del personaggio, quindi l'immagine della sprite arma non terrà conto dell'omino per dire. Guardare terza riga dell'immagine caricata 
![immagine del cavolo](https://github.com/user-attachments/assets/851b64af-33c7-4d8a-9d56-543aa674422c)

**Comment by alessandromanca98** [comment]
Nei frame delle animazioni delle armi, per ridurre il carico di lavoro fai frame molto grandi (ben più del pg), posiziona il frame del pg su un livello mentre disegni, più o meno al centro del frame, e posiziona l'arma rispetto all'omino. Se per ciascuna animazione l'omino è posizionato nello stesso punto in ogni frame puoi mettere un offset unico per ciascuna animazione.
![esempio](https://github.com/user-attachments/assets/ded8b4f5-e3f5-467c-9ffd-fe3bab365bdf)
